/**
 * 
 */
package LexicalAnalyzer;

/**
 * @author marius
 * Token_Type
 */
public enum T_Type {
	ID, BREAK, CHAR, DOUBLE, ELSE, FOR, IF, 
	INT, RETURN, STRUCT, VOID, WHILE, CT_INT, 
	CT_REAL, CT_CHAR, CT_STRING, COMMA, SEMICOLON,
	LPAR, RPAR, LBRACKET, RBRACKET, LACC, RACC,
	ADD, SUB, MUL, DIV, DOT, AND, OR, NOT,
	ASSIGN, EQUAL, LESS, LESSEQ, GREATER,
	GREATEREQ, SPACE, LINECOMMENT, COMMENT, END; 
}
